name: Build and Push Docker Image
permissions:
  contents: read
  id-token: write
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello_world:latest

      - name: Verify Docker image pushed to Docker Hub
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/hello_world:latest
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DOCKERHUB_USERNAME }}", "password": "${{ secrets.DOCKERHUB_TOKEN }}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" -H "Authorization: JWT $TOKEN" https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/your-image-name/tags/latest/)
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Docker image was not found in Docker Hub."
            exit 1
          else
            echo "Docker image exists in Docker Hub."
          fi

      - name: Logout from DockerHub
        run: docker logout